/**
 * wc docusaurus nav <file> — Convert a Docusaurus sidebars.js to Mintlify navigation
 *
 * Reads a Docusaurus sidebars.js (CommonJS), converts the sidebar tree to
 * Mintlify docs.json navigation format, and writes JSON to stdout or a file.
 *
 * Output structure:
 *   - Single sidebar  → { anchors: [{ anchor, pages }] }
 *   - Multiple sidebars → { tabs: [{ tab, pages }] }
 */

import { createRequire } from "module";
import { resolve, join, relative, extname, dirname } from "path";
import { writeFileSync, existsSync, readFileSync, readdirSync, statSync } from "fs";
import chalk from "chalk";

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * @param {string} file  - Path to sidebars.js (or sidebars.ts)
 * @param {Object} options
 * @param {string} [options.prefix]   - Path prefix to prepend to every page ID (e.g. "docs")
 * @param {string} [options.docsDir]  - Docs folder for autogenerated items (default: docs/ next to sidebars.js)
 * @param {string} [options.output]   - Write result to this file instead of stdout
 * @param {boolean} options.quiet
 */
export async function docusaurusNav(file, options = {}) {
  const verbose = !options.quiet;
  const absFile = resolve(process.cwd(), file);

  if (!existsSync(absFile)) {
    console.error(chalk.red(`Error: File not found: ${absFile}`));
    process.exit(1);
  }

  // Load the sidebars module (CommonJS)
  let sidebars;
  try {
    const req = createRequire(absFile);
    sidebars = req(absFile);
  } catch (e) {
    // Fallback: try to extract the exports by parsing the file as text
    try {
      sidebars = evalSidebarsFile(absFile);
    } catch {
      console.error(chalk.red(`Error loading ${file}: ${e.message}`));
      process.exit(1);
    }
  }

  if (!sidebars || typeof sidebars !== "object") {
    console.error(chalk.red(`Error: ${file} did not export an object`));
    process.exit(1);
  }

  const prefix = options.prefix ? options.prefix.replace(/\/+$/, "") : "";
  const keys = Object.keys(sidebars);

  if (keys.length === 0) {
    console.error(chalk.red(`Error: No sidebar keys found in ${file}`));
    process.exit(1);
  }

  // Resolve the docs directory for autogenerated items
  const sidebarDir = dirname(absFile);
  let docsDir = null;
  if (options.docsDir) {
    docsDir = resolve(process.cwd(), options.docsDir);
  } else {
    // Default: docs/ next to sidebars.js, or the sidebars.js directory itself
    const candidate = join(sidebarDir, "docs");
    docsDir = existsSync(candidate) ? candidate : sidebarDir;
  }

  const navigation = buildNavigation(sidebars, keys, prefix, docsDir);
  const json = JSON.stringify(navigation, null, 2);
  const outFile = options.output || "nav.json";
  const outPath = resolve(process.cwd(), outFile);

  writeFileSync(outPath, json, "utf-8");

  if (verbose) {
    const pageCount = countPages(navigation);
    console.log(chalk.green(`✓ Navigation written to ${outFile}`) +
      chalk.dim(` (${pageCount} pages, ${keys.length} sidebar${keys.length !== 1 ? "s" : ""})`));
  }
}

// ---------------------------------------------------------------------------
// Navigation builder
// ---------------------------------------------------------------------------

function buildNavigation(sidebars, keys, prefix, docsDir) {
  if (keys.length === 1) {
    const pages = convertItems(sidebars[keys[0]], prefix, docsDir);
    return {
      anchors: [
        {
          anchor: labelFromKey(keys[0]),
          pages,
        },
      ],
    };
  }

  // Multiple sidebars → tabs
  const tabs = keys.map((key) => ({
    tab: labelFromKey(key),
    pages: convertItems(sidebars[key], prefix, docsDir),
  }));
  return { tabs };
}

function convertItems(items, prefix, docsDir) {
  if (!Array.isArray(items)) return [];
  return items.flatMap((item) => {
    const result = convertItem(item, prefix, docsDir);
    // autogenerated returns an array; everything else returns a single item
    if (Array.isArray(result)) return result;
    return result ? [result] : [];
  });
}

function convertItem(item, prefix, docsDir) {
  if (typeof item === "string") {
    return prefix ? `${prefix}/${item}` : item;
  }

  if (!item || typeof item !== "object") return null;

  switch (item.type) {
    case "category":
      return {
        group: item.label,
        pages: convertItems(item.items || [], prefix, docsDir),
      };

    case "doc":
      // { type: 'doc', id: 'foo/bar', label: 'Foo' }
      if (item.id) return prefix ? `${prefix}/${item.id}` : item.id;
      return null;

    case "autogenerated":
      // { type: 'autogenerated', dirName: 'faq' }
      if (!item.dirName) return null;
      return expandAutogenerated(item.dirName, docsDir, prefix);

    case "link":
    case "html":
      // External links and raw HTML separators — skip
      return null;

    case "ref":
      // Cross-sidebar reference — treat like a doc
      if (item.id) return prefix ? `${prefix}/${item.id}` : item.id;
      return null;

    default:
      // Unknown type or no type — skip
      return null;
  }
}

// ---------------------------------------------------------------------------
// Autogenerated sidebar expansion
// ---------------------------------------------------------------------------

const MD_EXTS = new Set([".md", ".mdx"]);

/**
 * Walks `docsDir/dirName` and builds the same page/group structure that
 * Docusaurus would generate, respecting:
 *   - `_category_.json` for folder label and position
 *   - frontmatter `sidebar_position` for file ordering
 *   - alphabetical fallback when positions are equal / absent
 *   - files/dirs starting with `_` are skipped (Docusaurus convention)
 *
 * @returns {Array} flat array of page strings and group objects
 */
function expandAutogenerated(dirName, docsDir, prefix) {
  if (!docsDir) return [];
  const dirPath = join(docsDir, dirName);
  if (!existsSync(dirPath)) return [];
  return walkAutoDir(dirPath, docsDir, prefix);
}

function walkAutoDir(dirPath, docsDir, prefix) {
  let entries;
  try { entries = readdirSync(dirPath); } catch { return []; }

  const items = []; // { position, sortKey, value }

  for (const entry of entries) {
    // Skip hidden and Docusaurus-private files/dirs (but allow _category_.json reads below)
    if (entry.startsWith("_")) continue;

    const fullPath = join(dirPath, entry);
    let stat;
    try { stat = statSync(fullPath); } catch { continue; }

    if (stat.isDirectory()) {
      // Read _category_.json for label + position
      let label = labelFromDir(entry);
      let position = Infinity;
      const catPath = join(fullPath, "_category_.json");
      if (existsSync(catPath)) {
        try {
          const cat = JSON.parse(readFileSync(catPath, "utf-8"));
          if (cat.label) label = cat.label;
          if (cat.position != null) position = Number(cat.position);
        } catch { /* ignore malformed */ }
      }

      const pages = walkAutoDir(fullPath, docsDir, prefix);
      if (pages.length > 0) {
        items.push({ position, sortKey: label.toLowerCase(), value: { group: label, pages } });
      }
    } else {
      const ext = extname(entry).toLowerCase();
      if (!MD_EXTS.has(ext)) continue;

      // Doc ID: path relative to docsDir, no extension
      const relPath = relative(docsDir, fullPath).replace(/\.mdx?$/, "").replace(/\\/g, "/");
      const pageId = prefix ? `${prefix}/${relPath}` : relPath;

      // Read sidebar_position from frontmatter
      let position = Infinity;
      try {
        const src = readFileSync(fullPath, "utf-8");
        const m = src.match(/^sidebar_position\s*:\s*(\d+(?:\.\d+)?)/im);
        if (m) position = parseFloat(m[1]);
      } catch { /* ignore */ }

      items.push({ position, sortKey: relPath.toLowerCase(), value: pageId });
    }
  }

  // Sort: by position asc, then alphabetically
  items.sort((a, b) => {
    if (a.position !== b.position) return a.position - b.position;
    return a.sortKey.localeCompare(b.sortKey);
  });

  return items.map((i) => i.value);
}

/** Convert a directory name to a readable label (strips leading digits+dash, capitalises) */
function labelFromDir(name) {
  return name
    .replace(/^\d+[-_]/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert camelCase / snake_case key to Title Case label */
function labelFromKey(key) {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/[_-]/g, " ")
    .replace(/^\w/, (c) => c.toUpperCase())
    .trim();
}

function countPages(nav) {
  let n = 0;
  function walk(arr) {
    if (!Array.isArray(arr)) return;
    for (const item of arr) {
      if (typeof item === "string") { n++; }
      else if (item?.pages) walk(item.pages);
      else if (item?.groups) walk(item.groups);
    }
  }
  // nav may be { tabs } or { anchors }
  const top = nav.tabs || nav.anchors || [];
  for (const entry of top) walk(entry.pages || []);
  return n;
}

// ---------------------------------------------------------------------------
// Fallback: evaluate sidebars.js as a script when require() fails
// (e.g. TypeScript or ESM-style files)
// ---------------------------------------------------------------------------

function evalSidebarsFile(absFile) {
  const src = readFileSync(absFile, "utf-8");
  // Strip TypeScript type annotations in simple cases: `: SidebarsConfig`
  const stripped = src
    .replace(/:\s*SidebarsConfig\b/g, "")
    .replace(/^export\s+default\s+/, "module.exports = ");

  // eslint-disable-next-line no-new-func
  const fn = new Function("module", "exports", "require", "__filename", "__dirname", stripped);
  const mod = { exports: {} };
  fn(mod, mod.exports, () => ({}), absFile, resolve(absFile, ".."));
  return mod.exports;
}
